site_name: pytest-expecter
site_description: Better testing with expecter and pytest.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/pytest-expecter
edit_uri: https://github.com/jacebrowning/pytest-expecter/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Basic Usage: usage.md
  - Builtin Checks: checks.md
  - Custom Checks: custom.md
  - About:
      - Release Notes: about/changelog.md
      - Contributing: about/contributing.md
      - License: about/license.md
