site_name: pytest-expecter
site_description: Better testing with expecter and pytest.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/pytest-expecter
edit_uri: https://github.com/jacebrowning/pytest-expecter/edit/jacebrowning/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
- Home: index.md
- Usage: usage.md
- Checks: checks.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
