site_name: pytest-expecter
site_description: Better testing with expecter and pytest.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/pytest-expecter

theme: readthedocs

pages:
- Home: index.md
- Examples: examples.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
